### ISSUE TITLE
Language redirect not working since 1.14

### ISSUE THREAD

**Issue by 0x3e4** [seatsurfing/backend#166]
I receive the following HTTP 502 "Bad Gateway" error as a local admin user since the update to 1.14:

Url: https://_FQDN_/admin/dashboard/
Error: Get "http://localhost:3000/admin/en/dashboard": dial tcp 127.0.0.1:3000: connect: connection refused

When i manually update the url with ../en/.. or ../de/.. then the frontend is working. As a local user the booking-ui redirect is working as expected but when i login with a OAuth user (Microsoft) then i receive a similar error like above:

Url: https://_FQDN_/ui/login/success/_000-0-0-0-000_
Error: Get "http://localhost:3001/ui/en/login/success/000-0-0-0-000": dial tcp 127.0.0.1:3001: connect: connection refused

Manually fixing the url works here too.
For testing purposes i already set up a new test instance because i initially thought that changing the environment configuration parameter `INIT_ORG_LANGUAGE: 'de'` after the first start of the instance was the issue but it looks like that version 1.14 has a bug here..?
Also tried to remove and update the language entry directly in the "organizations" psql table but nothing changed.

hats off for the project!

**Comment by GabrieleV** [comment]
Confirmed in latest docker image as of now.
Had to downgrade to 1.13.8 after failing.

**Comment by virtualzone** [comment]
Fixed in latest ```dev```-tagged Docker image. You'll need to add the environment variable ```FRONTEND_URL``` to both the Booking UI and the Admin UI containers, such as:

```
  - image: docker.io/seatsurfing/admin-ui:dev
    name: adminui
    env:
    - name: FRONTEND_URL
      value: "https://seatsurfing.your-domain.com"
```

**Comment by virtualzone** [comment]
Fixed in version 1.14.1.

**Comment by 0x3e4** [comment]
hmm.. i tried the new release twice but i still face issues like #171
